[package]
name = "winterm"
version = "0.2.0"
edition = "2021"
description= "A Rust library to create a pixelated window inside a terminal"
repository = "https://github.com/clbrunet/winterm"
license = "MIT"

[dependencies]
crossterm = "0.23"
nalgebra = "0.31.0"
