[package]
name = "winterm"
version = "0.3.0"
edition = "2021"
description= "A Rust library to create a pixelated window inside a terminal"
repository = "https://github.com/clbrunet/winterm"
license = "MIT"

[dependencies]
crossterm = "0.24.0"
nalgebra = "0.31.0"
